version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_persona
    environment:
      SA_PASSWORD: "Admin123!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - persona-network
    restart: always

volumes:
  sqlserver_data:

networks:
  persona-network:
    driver: bridge
